@echo off
echo Installing root dependencies...
npm install
echo Installing frontend dependencies...
cd frontend
npm install
cd ..
echo Starting local blockchain...
start "Hardhat Node" cmd /k "npm run node"
timeout /t 5 /nobreak > nul
echo Deploying contracts...
start "Deploy" cmd /k "npm run deploy:localhost"
timeout /t 10 /nobreak > nul
echo Starting frontend...
start "Frontend" cmd /k "npm run frontend"
echo Setup complete. Check the opened command windows for status.
